mode: test
filtering_algorithm: item-based
user-based:
  cosine_similarity: False
  pearson_correlation: True
  euclidean_distance: False
  IUF: False
  case_amplification: True
  k: -1
  similarity_threshold: 0






